<?php
	$setting = Mage::helper('em0120settings');
	$checkmobile = $setting-> checkMobilePhp();
?>
<?php if (!$checkmobile):?>
<div class="visible-sm visible-md visible-lg">
    <?php
       /* get config from themesetting */
		$setting = Mage::helper('em0120settings');
		$fonts = Mage::getModel('em0120settings/config_font')->toOptionArray();
		$bg_url="skin/frontend/default/em0120/images/stripes/";
		$boxwide = Mage::getModel('em0120settings/config_boxwide')->toOptionArray();
		$ischecked = $setting->getGeneral_WideslideFull();
    ?>
    <a href="javascript:void(0)" class="btn-toggle">+ open/close</a>
    <div id="demotool_variation">
       <div class="variation-cp" style="display:none">
          <div class="demotool-title">Magento Theme Variations</div>
          <form method="get" id="emvariationform" action="<?php echo $this->getSkinUrl('css/variation.php') ?>">
             <div class="demotool-content">
                <!-- Google Fonts -->
                <div class="demo demo-google-fonts">
                   <div class="content-title"><span>Google Fonts</span></div>
                   <div class="wrapper-content google-fonts-setting">
                      <div class="box last">
                         <div class="content">
                            <div class="col">
                               <div class="row">
                                  <div class="label">Import these google fonts</div>
                                  <div class="input">
                                     <select id="em_variation_google_font" multiple="multiple" rows='10' size='10' >
                                        <?php $selectedFonts = explode(',', $setting->getTypography_GoogleFonts()) ?>
                                        <?php foreach ($fonts as $_font): ?>
                                        <option value="<?php echo htmlspecialchars($_font['value']) ?>" <?php echo @in_array($_font['value'], $selectedFonts) ? 'selected="selected"' : '' ?>><?php echo $_font['label'] ?></option>
                                        <?php endforeach ?>
                                     </select>
                                  </div>
                                  <div class="desc">Select which google fonts should be imported to your site</div>
                               </div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
                <!-- Element Fonts -->
                <div class="demo demo-fonts">
                   <div class="content-title"><span>Element Fonts</span></div>
                   <div class="wrapper-content fonts-setting">
                      <div class="box last">
                         <div class="content">
                            <div class="col">
                               <div class="row">
    								<div class="label">General Font</div>
    								<div class="input"><input type="text" name="general_font" value="<?php echo htmlspecialchars($setting->getTypography_GeneralFont()) ?>" class="input-text"/></div>
    								<div class="desc">Font for body, content, text...<br/>E.g. <em>normal 13px/1.35 Arial, Helvetica, sans-serif</em></div>
    							</div>
                               <div class="row">
                                  <div class="label">H1</div>
                                  <div class="input"><input type="text" name="h1" value="<?php echo htmlspecialchars($setting->getTypography_H1Font()) ?>" class="input-text" /></div>
                                  <div class="desc">Font of H1 element and other similar h1 heading.<br/>E.g. <em>500 30px/1.35 Playfair Display,Arial,Helvetica,sans-serif</em></div>
                               </div>
                               <div class="row">
                                  <div class="label">H2</div>
                                  <div class="input"><input type="text" name="h2" value="<?php echo htmlspecialchars($setting->getTypography_H2Font()) ?>" class="input-text" /></div>
                                  <div class="desc">Font of H2 element and other similar h2 heading.<br/>E.g. <em>500 24px/1.35 Playfair Display,Arial,Helvetica,sans-serif</em></div>
                               </div>
                               <div class="row">
                                  <div class="label">H3</div>
                                  <div class="input"><input type="text" name="h3" value="<?php echo htmlspecialchars($setting->getTypography_H3Font()) ?>" class="input-text" /></div>
                                  <div class="desc">Font of H3 element and other similar h3 heading.<br/>E.g. <em>400 18px/1.35 Roboto Slab,Arial,Helvetica,sans-serif</em></div>
                               </div>
                               <div class="row">
                                  <div class="label">H4</div>
                                  <div class="input"><input type="text" name="h4" value="<?php echo htmlspecialchars($setting->getTypography_H4Font()) ?>" class="input-text" /></div>
                                  <div class="desc">Font of H4 element and other similar h4 heading.<br/>E.g. <em>500 15px/1.35 Roboto Slab,Arial,Helvetica,sans-serif</em></div>
                               </div>
                               <div class="row">
                                  <div class="label">H5</div>
                                  <div class="input"><input type="text" name="h5" value="<?php echo htmlspecialchars($setting->getTypography_H5Font()) ?>" class="input-text" /></div>
                                  <div class="desc">Font of H5 element and other similar h5 heading.<br/>E.g. <em>400 12px/1.35 Roboto Slab,Arial,Helvetica,sans-serif</em></div>
                               </div>
                               <div class="row">
                                  <div class="label">H6</div>
                                  <div class="input"><input type="text" name="h6" value="<?php echo htmlspecialchars($setting->getTypography_H6Font()) ?>" class="input-text" /></div>
                                  <div class="desc">Font of H5 element and other similar h5 heading.<br/>E.g. <em>400 10px/1.35 Open Sans,Arial,Helvetica,sans-serif</em></div>
                               </div>
							   <div class="row">
                                  <div class="label">Title Banner</div>
                                  <div class="input"><input type="text" name="h6" value="<?php echo htmlspecialchars($setting->getTypography_BannerTitleFont()) ?>" class="input-text" /></div>
                                  <div class="desc">Font of title banner.<br/>E.g. <em>500 44px Playfair Display, Arial, Times New Roman, serif</em></div>
                               </div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
                
                <!-- General -->
    			<div class="demo demo-general">
    				<div class="content-title"><span>General Config</span></div>
    				<div class="wrapper-content general-setting">
    					<div class="box last">
    						<div class="content">
    							<div class="col">
                                    <div class="row">
    									<div class="label">Box/Wide Mode</div>
    									<div class="input">
                                            <select id="em_box_wide" name="em_box_wide" class="em_box_wide select">
                                                <?php $selectedBoxWide = explode(',', $setting->getGeneral_BoxWide()) ?>
                                                <?php foreach ($boxwide as $boxwide_item): ?>
    											     <option value="<?php echo htmlspecialchars($boxwide_item['value']) ?>" <?php echo @in_array($boxwide_item['value'], $selectedBoxWide) ? 'selected="selected"' : '' ?>><?php echo $boxwide_item['label'] ?></option>
    											<?php endforeach ?>
                                            </select>
    									</div>
    									<div class="desc">Default: Wide</div>
    								</div>	
									<div class="row" id="emoption_wideslideshow">
										<div class="input">
											<input id="wide_full" class="full_slideshow" type="checkbox" name="wide_full" value="wide_full" <?php if($ischecked!=0):?>checked="checked"<?php endif;?> /><span>Full Slideshow</span>
										</div>
									</div>							
                                    <div id="page_boxconfig">
                                        <div class="row">
        									<div class="label">Page Background Color</div>
        									<div class="input"><input type="text" name="page_bg_color" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgColor()) ?>" class="color-picker" /></div>
        									<div class="desc">Default #ffffff</div>
        								</div>                                    
                                        <div class="row">
        									<div class="label">Page Background Pattern</div>
                                            <div class="input">
                                                 <input type="hidden" name="page_bg_image" value="<?php echo htmlspecialchars($setting->getTypography_PageBgImage()) ?>"  />
                                                 <?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0120/images/stripes/'; ?>                                 
                                                 <?php foreach (Mage::getModel('em0120settings/config_stripes')->toOptionArray() as $row):?>
                                                 <?php $img_url = $imgDir . $row['value']; ?>
                                                 <?php $imgBgUrl = $bg_url . $row['value']; ?>
                                                 <a href="#" class="page_bg_image" data-input-value="<?php echo $imgBgUrl; ?>" <?php echo $setting->getTypography_PageBgImage() == $row['value'] ? 'style="selected=\'selected\'"' : '' ?>>
                                                 <img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $img_url ?>)" alt="" />
                                                 </a>
                                                 <?php endforeach ?>
                                              </div>
        									<div class="desc">Specify background pattern image.</div>
        								</div>
                                        <div class="row">
        									<div class="label">Page Background Position</div>
        									<div class="input"><input type="text" name="page_bg_position" value="<?php echo htmlspecialchars($setting->getTypography_PageBgPosition()) ?>" class="input-text"/></div>
        									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
        								</div>
                                        <div class="row">
        									<div class="label">Page Background Repeat</div>
        									<div class="input"><input type="text" name="page_bg_repeat" value="<?php echo htmlspecialchars($setting->getTypography_PageBgRepeat()) ?>" class="input-text"/></div>
        									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
        								</div>
                                        <div class="row">
        									<div class="label">Box Shadow</div>
        									<div class="input"><input type="text" name="box_shadow" value="<?php echo htmlspecialchars($setting->getTypography_BoxShadow()) ?>" class="input-text"/></div>
        									<div class="desc">Configure box shadow for menu, product, box... <br/>Default: 0 0px 10px #dddddd.</div>
        								</div>
										<div class="row">
        									<div class="label">Box Shadow 2</div>
        									<div class="input"><input type="text" name="box2_shadow" value="<?php echo htmlspecialchars($setting->getTypography_Box2Shadow()) ?>" class="input-text"/></div>
        									<div class="desc">Configure box shadow for product home page. <br/>Default: 0px 1px 8px #edeaea inset.</div>
        								</div>
        								<div class="row">
        									<div class="label">Rounded Corner</div>
        									<div class="input"><input type="text" name="rounded_corner" value="<?php echo htmlspecialchars($setting->getTypography_RoundedCorner()) ?>" class="input-text"/></div>
        									<div class="desc">Configure box shadow for box, inpurt, textarea, select,... <br/> Default: 0px</div>
        								</div>
                                    </div>
    							</div>
    						</div>
    					</div>
    				</div>					
    			</div>
                
                <!-- Header -->
                <div class="demo demo-header">
                   <div class="content-title"><span>Header</span></div>
                   <div class="wrapper-content header-setting">
                      <div class="box last">
                         <div class="content">
                            <div class="col col-1">
                               <div class="row">
                                  <div class="label">Header Background Color</div>
                                  <div class="input"><input type="text" name="header_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Background color in header.<br/>Syntax: #number or rgba(...)<br/> Default: #ffffff</div>
                               </div>
                               <div class="row">
                                  <div class="label">Header Text 2 Color</div>
                                  <div class="input"><input type="text" name="header_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in header top.<br/> Default: #ffffff</div>
                               </div>
							   <div class="row">
                                  <div class="label">Header Line Color</div>
                                  <div class="input"><input type="text" name="header_line_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderLineColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Line color used in search,... <br/> Default: #dcdcdc</div>
                               </div>
    						</div>
                            <div class="col col-1">
                               <div class="row">
                                  <div class="label">Header Background 2 Color</div>
                                  <div class="input"><input type="text" name="header_bg2_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBg2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Background color in header top.<br/> Default: #222222</div>
                               </div>
                               <div class="row">
                                  <div class="label">Header Text 3 Color</div>
                                  <div class="input"><input type="text" name="header_text3_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText3Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in search,dropdown cart. <br/> Default: #999999</div>
                               </div>
							   <div class="row">
                                  <div class="label">Header Line 2 Color</div>
                                  <div class="input"><input type="text" name="header_line2_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderLine2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Line color used in search hover.<br/> Default: #000000</div>
                               </div>
							</div>
                            <div class="col col-1">
                               <div class="row">
                                  <div class="label">Header Text Color</div>
                                  <div class="input"><input type="text" name="header_text_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderTextColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in header. <br/> Default: #666666</div>
                               </div>
                               <div class="row">
                                  <div class="label">Header Text 4 Color</div>
                                  <div class="input"><input type="text" name="header_text4_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText4Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in header when hover.<br/> Default: #b95b79</div>
                               </div>
    						   	<div class="row">
                                  <div class="label">Header Line 3 Color</div>
                                  <div class="input"><input type="text" name="header_line3_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderLine3Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Line color used in dropdown.  <br/> Default: #bdbdbd</div>
                               </div>
                            </div>
                            <div class="col">
                               <div class="row">
                                  <div class="label">Header Background Pattern</div>
                                  <div class="input">
                                     <input type="hidden" name="header_bg_image" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgImage()) ?>"  />
                                     <?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0120/images/stripes/'; ?>                                 
                                     <?php foreach (Mage::getModel('em0120settings/config_stripes')->toOptionArray() as $row):?>
                                     <?php $img_url = $imgDir . $row['value']; ?>
                                     <?php $imgBgUrl = $bg_url . $row['value']; ?>
                                     <a href="#" class="header_bg_image" data-input-value="<?php echo $imgBgUrl; ?>" <?php echo $setting->getTypography_HeaderBgImage() == $row['value'] ? 'style="selected=\'selected\'"' : '' ?>>
                                     <img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $img_url ?>)" alt="" />
                                     </a>
                                     <?php endforeach ?>
                                  </div>
                                  <div class="desc">Specify background pattern image.</div>
                               </div>
                               <div class="row">
    								<div class="label">Header Background Position</div>
    								<div class="input"><input type="text" name="header_bg_position" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgPosition()) ?>" class="input-text"/></div>
    								<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
    							</div>
                                <div class="row">
    								<div class="label">Header Background Repeat</div>
    								<div class="input"><input type="text" name="header_bg_repeat" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgRepeat()) ?>" class="input-text"/></div>
    								<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
    							</div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
                
                <!-- Top Menu -->
    			<div class="demo demo-topmenu">
    				<div class="content-title"><span>Top Menu</span></div>
    				<div class="wrapper-content topmenu-setting">
    					<div class="box last">
    						<div class="content">
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Top Menu Background Color</div>
    									<div class="input"><input type="text" name="topmenu_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuBgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default:transparent</div>
    								</div>
    								<div class="row">
    									<div class="label">Top Menu Text Color</div>
    									<div class="input"><input type="text" name="topmenu_text_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuTextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default: #000000</div>
    								</div>
									<div class="row">
    									<div class="label">Top Menu Line Color</div>
    									<div class="input"><input type="text" name="topmenu_line_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuLineColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default: #b58719</div>
    								</div> 
								</div>
                                <div class="col col-1">
									<div class="row">
    									<div class="label">Top Menu Background 2 Color </div>
    									<div class="input"><input type="text" name="topmenu_bg2_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuBg2Color()) ?>" class="color-picker" /></div>
    									<div class="desc">Background color used in freezed top menu. <br /> Default: #000000</div>
    								</div>
									<div class="row">
    									<div class="label">Top Menu Text 2 Color </div>
    									<div class="input"><input type="text" name="topmenu_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuText2Color()) ?>" class="color-picker" /></div>
    									<div class="desc">Text color used in freezed top menu. <br /> Default: #ffffff</div>
    								</div>
									
                                                                                                
                                </div>
                                <div class="col col-1">
									<div class="row">
    									<div class="label">Top Menu Hover Background Color</div>
    									<div class="input"><input type="text" name="topmenu_hover_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuHoverBgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default: transparent</div>
    								</div>
									<div class="row">
    									<div class="label">Top Menu Hover Text Color</div>
    									<div class="input"><input type="text" name="topmenu_hover_text_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuHoverTextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default: #b95b79</div>
    								</div>
									
								</div>
                                <div class="col">                              
                                    <div class="row">
    									<div class="label">Top Menu Font</div>
    									<div class="input"><input type="text" name="topmenu_font" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuFont()) ?>" class="input-text"/></div>
    									<div class="desc">Default: 500 15px/1.35 Roboto Slab,Arial, Helvetica, sans-serif</div>
    								</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Dropdown Menu -->
    			<div class="demo demo-dropmenu">
    				<div class="content-title"><span>Dropdown Menu</span></div>
    				<div class="wrapper-content dropmenu-setting">
    					<div class="box last">
    						<div class="content">
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Dropdown Menu Background Color</div>
    									<div class="input"><input type="text" name="dropmenu_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuBgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default: #ffffff<br/><br/><br/></div>
    								</div>
									<div class="row">
    									<div class="label">Dropdown Menu Hover Text Color</div>
    									<div class="input"><input type="text" name="dropmenu_hover_text_color" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuHoverTextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default: #b95b79</div>
    								</div>
								</div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Dropdown Menu Text Color</div>
    									<div class="input"><input type="text" name="dropmenu_text_color" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuTextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Text color used in menu drop title.<br/>Default: #666666</div>
    								</div>                                                               
									<div class="row">
    									<div class="label">Dropdown Menu Line Color</div>
    									<div class="input"><input type="text" name="dropmenu_line_color" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuLineColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default: #bdbdbd</div>
    								</div>  
								</div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Dropdown Menu Text 2 Color</div>
    									<div class="input"><input type="text" name="dropmenu_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuText2Color()) ?>" class="color-picker" /></div>
    									<div class="desc">Default text color used normal text. <br/>Default: #999999</div>
    								</div>
                                </div>
                                
                                <div class="col">                                
                                    <div class="row">
    									<div class="label">Dropdown Menu Font</div>
    									<div class="input"><input type="text" name="dropmenu_font" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuFont()) ?>" class="input-text"/></div>
    									<div class="desc">Default font used normal text.<br/>Default: normal 12px/1.35 Open Sans,Arial,Helvetica,sans-serif</div>
    								</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Body -->
                <div class="demo demo-body">
                   <div class="content-title"><span>Body</span></div>
                   <div class="wrapper-content body-setting">
                      <div class="box last">
                         <div class="content">
                            <div class="col col-1">
                               <div class="row">
                                  <div class="label">Body Background Color</div>
                                  <div class="input"><input type="text" name="body_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Background color of body.<br/>Syntax: #number or rgba(...)<br/> Default: #ffffff</div>
                               </div>
                               <div class="row">
                                  <div class="label">Body Background 4 Color</div>
                                  <div class="input"><input type="text" name="body_bg4_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg4Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Background color instock, page hover,... <br/> Default: #b95b79</div>
                               </div>
                               <div class="row">
                                  <div class="label">Body Text 2 Color</div>
                                  <div class="input"><input type="text" name="body_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used navigation, title reviews...<br/> Default: #666666</div>
                               </div>
							   <div class="row">
                                  <div class="label">Body Text 5 Color</div>
                                  <div class="input"><input type="text" name="body_text5_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText5Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in label hover, table, tags... <br/> Default: #ffffff</div>
                               </div>
								<div class="row">
                                  <div class="label">Body Line 3 Color</div>
                                  <div class="input"><input type="text" name="body_line3_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyLine3Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Line color used in hover/acitve input,... <br/> Default: #000000</div>
                               </div> 					   
                            </div>
                            <div class="col col-1">
                               <div class="row">
                                  <div class="label">Body Background 2 Color</div>
                                  <div class="input"><input type="text" name="body_bg2_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Background color in block,... <br/> Default: #63360e</div>
                               </div>
                               <div class="row">
                                  <div class="label">Body Background 5 Color</div>
                                  <div class="input"><input type="text" name="body_bg5_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg5Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Background color in table,.... <br/> Default: #bdbdbd</div>
                               </div>
							   <div class="row">
                                  <div class="label">Body Text 3 Color</div>
                                  <div class="input"><input type="text" name="body_text3_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText3Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in hover, total price, title checkout steps,... <br/> Default: #000000</div>
                               </div>
                                <div class="row">
                                  <div class="label">Body Line Color</div>
                                  <div class="input"><input type="text" name="body_line_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyLineColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Line color used in  popular line,... <br/> Default: #cecece</div>
                               </div>                           
                            </div>
                            <div class="col col-1">
                               <div class="row">
                                  <div class="label">Body Background 3 Color</div>
                                  <div class="input"><input type="text" name="body_bg3_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg3Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Background color in  tags, qty,...<br/> Default: #ee217a</div>
                               </div>
                               <div class="row">
                                  <div class="label">Body Text Color</div>
                                  <div class="input"><input type="text" name="body_text_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyTextColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in default,... <br/> Default: #999999</div>
                               </div>
							   <div class="row">
                                  <div class="label">Body Text 4 Color</div>
                                  <div class="input"><input type="text" name="body_text4_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText4Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in price, product name, title sidebar,... <br/> Default: #b95b79</div>
                               </div>
								<div class="row">
                                  <div class="label">Body Line 2 Color</div>
                                  <div class="input"><input type="text" name="body_line2_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyLine2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Line color used in block. <br/> Default: #edf2ee</div>
                               </div>
                            </div>
                            <div class="col">
                               <div class="row">
                                  <div class="label">Body Background Pattern</div>
                                  <div class="input">
                                     <input type="hidden" name="body_bg_image" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgImage()) ?>"  />
                                     <?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0120/images/stripes/'; ?>                                 
                                     <?php foreach (Mage::getModel('em0120settings/config_stripes')->toOptionArray() as $row):?>
                                     <?php $img_url = $imgDir . $row['value']; ?>
                                     <?php $imgBgUrl = $bg_url . $row['value']; ?>
                                     <a href="#" class="body_bg_image" data-input-value="<?php echo $imgBgUrl; ?>" <?php echo $setting->getTypography_BodyBgImage() == $row['value'] ? 'style="selected=\'selected\'"' : '' ?>>
                                     <img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $img_url ?>)" alt="" />
                                     </a>
                                     <?php endforeach ?>
                                  </div>
                                  <div class="desc">Specify background pattern image.</div>
                               </div>
                               <div class="row">
    								<div class="label">Body Background Position</div>
    								<div class="input"><input type="text" name="header_bg_position" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgPosition()) ?>" class="input-text"/></div>
    								<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
    							</div>
                                <div class="row">
    								<div class="label">Body Background Repeat</div>
    								<div class="input"><input type="text" name="header_bg_repeat" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgRepeat()) ?>" class="input-text"/></div>
    								<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
    							</div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
                
                <!-- Footer -->
                <div class="demo demo-footer">
                   <div class="content-title"><span>Footer</span></div>
                   <div class="wrapper-content footer-setting">
                      <div class="box last">
                         <div class="content">
                            <div class="col col-1">
                               <div class="row">
                                  <div class="label">Footer Background Color</div>
                                  <div class="input"><input type="text" name="footer_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Background color in footer.<br/>Syntax: #number or rgba(...)<br/> Default: #222222</div>
                               </div>
							    <div class="row">
                                  <div class="label">Footer Text 2 Color</div>
                                  <div class="input"><input type="text" name="footer_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterText2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in title footer. <br/> Default: #ffffff</div>
                               </div>
                               <div class="row">
                                  <div class="label">Footer Line Color</div>
                                  <div class="input"><input type="text" name="footer_line_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterLineColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Line-color in footer.<br/> Default: #c26f89</div>
                               </div> 
							   
    						</div>
                            <div class="col col-1">
                               <div class="row">
                                  <div class="label">Footer Background 2 Color</div>
                                  <div class="input"><input type="text" name="footer_bg2_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterBg2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Back ground color in footer. <br/> Default: #b95b79</div>
                               </div>
							   <div class="row">
                                  <div class="label">Footer Text 3 Color</div>
                                  <div class="input"><input type="text" name="footer_text3_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterText3Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in footer copy right. <br/> Default: #474747</div>
                               </div>
                               <div class="row">
                                  <div class="label">Footer Line 2 Color</div>
                                  <div class="input"><input type="text" name="footer_line2_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterLine2Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Line-color 2 in footer.<br/> Default: #ffffff</div>
                               </div> 
							                            
                            </div>
                            <div class="col col-1">
								<div class="row">
                                  <div class="label">Footer Text Color</div>
                                  <div class="input"><input type="text" name="footer_text_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderTextColor()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in footer. <br/> Default: #999999</div>
                               </div>
								<div class="row">
                                  <div class="label">Footer Text 4 Color</div>
                                  <div class="input"><input type="text" name="footer_text4_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText4Color()) ?>" class="color-picker" /></div>
                                  <div class="desc">Text color used in text support. <br/> Default: #b95b79</div>
                               </div>
                                
                            </div>
                            <div class="col">
                               <div class="row">
                                  <div class="label">Footer Background Pattern</div>
                                  <div class="input">
                                     <input type="hidden" name="footer_bg_image" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgImage()) ?>"  />
                                     <?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0120/images/stripes/'; ?>                                 
                                     <?php foreach (Mage::getModel('em0120settings/config_stripes')->toOptionArray() as $row):?>
                                     <?php $img_url = $imgDir . $row['value']; ?>
                                     <?php $imgBgUrl = $bg_url . $row['value']; ?>
                                     <a href="#" class="footer_bg_image" data-input-value="<?php echo $imgBgUrl; ?>" <?php echo $setting->getTypography_FooterBgImage() == $row['value'] ? 'style="selected=\'selected\'"' : '' ?>>
                                     <img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $img_url ?>)" alt="" />
                                     </a>
                                     <?php endforeach ?>
                                  </div>
                                  <div class="desc">Specify background pattern image.</div>
                               </div>
                               <div class="row">
    								<div class="label">Footer Background Position</div>
    								<div class="input"><input type="text" name="footer_bg_position" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgPosition()) ?>" class="input-text"/></div>
    								<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
    							</div>
                                <div class="row">
    								<div class="label">Footer Background Repeat</div>
    								<div class="input"><input type="text" name="footer_bg_repeat" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgRepeat()) ?>" class="input-text"/></div>
    								<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
    							</div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
                
                <!-- Button 1 -->
    			<div class="demo demo-button1">
    				<div class="content-title"><span>Button 1 - Default</span></div>
    				<div class="wrapper-content button1-setting">
    					<div class="box last">
    						<div class="content">
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 1 Background Color</div>
    									<div class="input"><input type="text" name="btn1_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn1BgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Background color used in default button... <br/> Default: #ffffff<br/></div>
    								</div>
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 1 Text Color</div>
    									<div class="input"><input type="text" name="btn1_text_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn1TextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Default text color used in default button.<br/>Default: #000000</div>
    								</div>                                                               
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 1 Line Color</div>
    									<div class="input"><input type="text" name="btn1_line_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn1LineColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Line color used in button 1<br/>Default: #dedede</div>
    								</div>
                                </div>
                                
                                <div class="col">                                
                                    <div class="row">
    									<div class="label">Button 1 Font</div>
    									<div class="input"><input type="text" name="btn1_font" value="<?php echo htmlspecialchars($setting->getTypography_Btn1Font()) ?>" class="input-text"/></div>
    									<div class="desc">Default font used in default button.<br/>Default: 500 14px/1.35 Open Sans,Arial, Helvetica, sans-serif</div>
    								</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Button 2 -->
    			<div class="demo demo-button1">
    				<div class="content-title"><span>Button 2 - Button Default Hover,...</span></div>
    				<div class="wrapper-content button2-setting">
    					<div class="box last">
    						<div class="content">
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 2 Background Color</div>
    									<div class="input"><input type="text" name="btn2_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn2BgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Background color used in button 2 <br/> Default: #000000<br/><br/><br/></div>
    								</div>
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 2 Text Color</div>
    									<div class="input"><input type="text" name="btn2_text_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn2TextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Text color used in button 2<br/>Default: #ffffff</div>
    								</div>                                                               
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 2 Line Color</div>
    									<div class="input"><input type="text" name="btn2_line_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn2LineColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Line color used in button 2<br/>Default: #000000</div>
    								</div>
                                </div>
                                
                               
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Button 3 -->
    			<div class="demo demo-button3">
    				<div class="content-title"><span>Button 3 - Button continue, update,... cart</span></div>
    				<div class="wrapper-content button3-setting">
    					<div class="box last">
    						<div class="content">
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 3 Background Color</div>
    									<div class="input"><input type="text" name="btn3_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn3BgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Background color used in button checkout 3 <br/> Default: #transparent <br/></div>
    								</div>
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 3 Text Color</div>
    									<div class="input"><input type="text" name="btn3_text_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn3TextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Text color used in button 3<br/>Default: #b95b79</div>
    								</div>                                                               
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 3 Line Color</div>
    									<div class="input"><input type="text" name="btn3_line_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn3LineColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Line color used in button 3<br/> Default: #b95b79</div>
    								</div>
                                </div>
                                
                                <div class="col">                                
                                    <div class="row">
    									<div class="label">Button 3 Font</div>
    									<div class="input"><input type="text" name="btn3_font" value="<?php echo htmlspecialchars($setting->getTypography_Btn3Font()) ?>" class="input-text"/></div>
    									<div class="desc">Default font used in button 3<br/>Default: 500 14px/1.35 Open Sans,Arial, Helvetica, sans-serif</div>
    								</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Button 4 -->
    			<div class="demo demo-button4">
    				<div class="content-title"><span>Button 4 - Button Checkout</span></div>
    				<div class="wrapper-content button4-setting">
    					<div class="box last">
    						<div class="content">
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 4 Background Color</div>
    									<div class="input"><input type="text" name="btn4_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn4BgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Background color used in button 4. <br/> Default: #b95b79<br/></div>
    								</div>
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 4 Text Color</div>
    									<div class="input"><input type="text" name="btn4_text_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn4TextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Text color used in button 4. <br/>Default: #ffffff</div>
    								</div>                                                               
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 4 Line Color</div>
    									<div class="input"><input type="text" name="btn4_line_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn4LineColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Line color used in button 4<br/>Default: #b95b79</div>
    								</div>
                                </div>
                                
                                <div class="col">                                
                                    <div class="row">
    									<div class="label">Button 4 Font</div>
    									<div class="input"><input type="text" name="btn4_font" value="<?php echo htmlspecialchars($setting->getTypography_Btn4Font()) ?>" class="input-text"/></div>
    									<div class="desc">Default font used in button 4. <br/>Default: 500 14px/1.35 Open Sans,Arial, Helvetica, sans-serif</div>
    								</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
				
				<!-- Button 5 -->
    			<div class="demo demo-button5">
    				<div class="content-title"><span>Button 5 - Button Slideshow, ... </span></div>
    				<div class="wrapper-content button5-setting">
    					<div class="box last">
    						<div class="content">
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 5 Background Color</div>
    									<div class="input"><input type="text" name="btn5_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn5BgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Background color used in button 5. <br/>Default: #transparent<br/></div>
    								</div>
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 5 Text Color</div>
    									<div class="input"><input type="text" name="btn5_text_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn5TextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Text color used in button 5. <br/>Default: #ffffff</div>
    								</div>                                                               
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 5 Line Color</div>
    									<div class="input"><input type="text" name="btn5_line_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn5LineColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Line color used in button 5<br/>Default: #ffffff</div>
    								</div>
                                </div>
                                
                                <div class="col">                                
                                    <div class="row">
    									<div class="label">Button 5 Font</div>
    									<div class="input"><input type="text" name="btn5_font" value="<?php echo htmlspecialchars($setting->getTypography_Btn5Font()) ?>" class="input-text"/></div>
    									<div class="desc">Default font used in button 5. <br/>Default:500 18px/1.35 Roboto Slab,Arial, Helvetica, sans-serif</div>
    								</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
				
				<!-- Button 6 -->
    			<div class="demo demo-button6">
    				<div class="content-title"><span>Button 6 - Button Slideshow Hover,...</span></div>
    				<div class="wrapper-content button6-setting">
    					<div class="box last">
    						<div class="content">
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 6 Background Color</div>
    									<div class="input"><input type="text" name="btn6_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn6BgColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Background color used in button 6. <br/>Default: #ffffff<br/></div>
    								</div>
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 6 Text Color</div>
    									<div class="input"><input type="text" name="btn6_text_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn6TextColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Text color used in button 6. <br/>Default: #000000</div>
    								</div>                                                               
                                </div>
                                
                                <div class="col col-1">
                                    <div class="row">
    									<div class="label">Button 6 Line Color</div>
    									<div class="input"><input type="text" name="btn6_line_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn6LineColor()) ?>" class="color-picker" /></div>
    									<div class="desc">Line color used in button 6<br/>Default: #ffffff</div>
    								</div>
                                </div>
                                
                                
                            </div>
                        </div>
                    </div>
                </div>
                             
                <a href="#" class="btn btn-primary btn-default reset-button" data-loading-text="Resetting..." >Reset</a>
             </div>
             <div class="copyright">Theme designed by <a href="http://emthemes.com/premium-magento-themes.html" title="Premium Magento Themes &amp; Premium Magento Templates" onclick="window.open('http://emthemes.com/premium-magento-themes.html');return false;">EMThemes.com</a></div>
          </form>
       </div>
    </div>
</div>
<?php endif;?>