<?php
	$_products = $this->getProductCollection();
	$_helper = $this->helper('catalog/output');
	
	$limitproduct = $this->getLimitCount();
	$size = $_products->getSize();
	if($limitproduct == "" || $limitproduct > $size){
		$limitproduct = $size;
	}
	
	$w = $this->getThumbnailWidth();
	$h = $this->getThumbnailHeight();
	$_columnCount = $this->getColumnCount();
	$alt_img = $this->getAltImg();
    
    /* slider config */
	$idJs = "slide_".md5(uniqid(rand()));    
    if ($this->getData('slider_unique_id'))
		$idJs = $this->getData('slider_unique_id');
	$this->idJs = $idJs;
?>
<div id="<?php echo $idJs;?>" <?php if($this->getCustomClass()): ?>class="<?php echo $this->getCustomClass();?>"<?php endif; ?>>
	<?php if($this->getFrontendTitle()): ?>
	<div class="widget-title em-widget-title">
		<h3><span><?php echo $this->getFrontendTitle(); ?></span></h3>
	</div>
	<?php endif; ?>
	<?php if($this->getFrontendDescription()):?>
	<div class="desc"><?php echo $this->getFrontendDescription(); ?></div>
	<?php endif ?>
	<?php if ($limitproduct): ?>
	<div class="widget em-filterproducts-grid">
		<div class="widget-products em-widget-products">
			<div class="wrapper-product-grid <?php if($this->getData('slider_enable')): ?>owl-carousel owl-theme<?php endif;?>">
				<?php $i=0; foreach ($_products as $_product): ?>
				<?php if ($_columnCount > 0 && $i%$_columnCount==0 || $_columnCount <= 0 && $i == 0): ?>
					<ul class="products-grid" style="<?php echo $this->getItemWidth() ? 'width:'.$this->getItemWidth().'px;' : '' ?>">
				<?php endif ?>
					<li class="<?php if($itemClass = $this->getData('item_class')) echo $itemClass.' '; ?>item <?php echo $_columnCount > 0 && $i%$_columnCount==0 || $_columnCount <= 0 && $i == 0 ?' first':''; ?><?php echo $_columnCount > 0 && ($i+1)%$_columnCount==0 || $i+1 == $limitproduct ?' last':''; ?>"
						style="<?php echo $this->getItemWidth() ? 'width:'.$this->getItemWidth().'px;' : '' ?> <?php echo $this->getItemHeight() ? 'height:'.$this->getItemHeight().'px;' : '' ?> <?php echo $this->getItemSpacing() ? 'margin-bottom:'.$this->getItemSpacing().'px;' : '' ?>">
						
						<div class="product-media">
							<?php if ($this->getShowFrontend('thumb')): ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
									<?php if ($this->getShowFrontend('label') && Mage::helper('core')->isModuleEnabled('EM_Productlabels')):?>
										<!--show label product - label extension is required-->
										<?php Mage::helper('productlabels')->display($_product);?>
									<?php endif;?>
									
									<?php if ($alt_img): ?>
										<img class="em-alt-hover img-responsive <?php if($this->getData('slider_lazyload')): ?>lazyOwl<?php endif;?>" <?php if($this->getData('slider_lazyload')): ?>data-src="<?php echo $this->helper('catalog/image')->init($_product, $alt_img)->resize($w,$h) ?>"<?php else:?>src="<?php echo $this->helper('catalog/image')->init($_product, $alt_img)->resize($w,$h) ?>"<?php endif;?> width="<?php echo $w; ?>" height="<?php echo $h ;?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
									<?php endif ?>
									<?php if($this->getData('slider_lazyload')): ?>
										<img class="lazyOwl <?php if ($alt_img): ?>em-alt-org<?php endif ?>" src="" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h) ?>" width="<?php echo $w; ?>" height="<?php echo $h ;?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
									<?php else:?>
										<img class="<?php if ($alt_img): ?>em-alt-org<?php endif ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h) ?>" width="<?php echo $w; ?>" height="<?php echo $h ;?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
									<?php endif;?>
									<span class="bkg-hover"></span>
								</a>
							<?php else: ?>
								<?php if ($this->getShowFrontend('label') && Mage::helper('core')->isModuleEnabled('EM_Productlabels')):?>
									<!--show label product - label extension is required-->
									<?php Mage::helper('productlabels')->display($_product);?>
								<?php endif;?>
							<?php endif; ?>

							<div class="hover-action">
								<div class="actions">
									<!--product add to cart-->
									<?php if ($this->getShowFrontend('addtocart')):?>
									<?php if ($_product->isSaleable()): ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
									<?php endif; ?>
									<!--product add to compare-wishlist-->
									<?php if($this->getShowFrontend('addto')):?>
									<ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
										<?php endif; ?>
									</ul>
									<?php endif; ?>
								</div>
							</div>
						</div>
						<div class="product-shop">
							<div class="f-fix">
								<?php if ($this->getShowFrontend('sku')):?>
								<p class="sku"><?php echo $_product->getSku(); ?></p>
								<?php endif ;?>
								
								<!--product name-->
								<?php if ($this->getShowFrontend('name')):?>
								<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
								<?php endif;?>
								
								<!--product description-->
								<?php if ($this->getShowFrontend('desc')):
									$desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
									if(strlen($desc)>80) {
										$strCutTitle = substr($desc, 0, 80);
										$desc = substr($strCutTitle, 0, strrpos($strCutTitle, ' '));
									}
									?>
								<p class="desc"><?php echo $desc; ?></p>
								<?php endif ;?>
								<!--product reviews-->
								<?php if ($this->getShowFrontend('review')):?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php endif ; ?>
								<!--product price-->
								<?php if ($this->getShowFrontend('price')):?>
									<?php if (Mage::helper('catalog')->canApplyMsrp($_product)):?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->__('Detail') ?></a>
									<?php else : ?>
										<?php $randomString = '-widget-new-list-'.substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 0, 7);?>
										<?php echo $this->getPriceHtml($_product, true, $randomString) ?>
									<?php endif;?>
								<?php endif;?>
							</div>
						</div>
					</li>
				<?php if ( $_columnCount > 0 && ($i+1)%$_columnCount==0 || $i+1==$limitproduct ): ?>
					</ul>
				<?php endif; ?>
				<?php $i++;?>
				<?php if($i >= $limitproduct) break;?>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
	<?php else:?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php endif; ?>
</div>
<?php if($this->getData('slider_enable')): ?>
<script type="text/javascript">
//<![CDATA[    
	function em_slider_init_widget_<?php echo $idJs ?>(){
        if(jQuery("#<?php echo $idJs ?>").find('div.owl-carousel').length){
            var owl = jQuery("#<?php echo $idJs ?>").find('div.owl-carousel'); 
            owl.owlCarousel({
                //Basic Speeds
                slideSpeed : <?php echo $this->getData('slider_speed') ? $this->getData('slider_speed') : '800' ?>,
                rewindSpeed : <?php echo $this->getData('slider_rewindspeed') ? $this->getData('slider_rewindspeed') : '800' ?>,
             
                //Autoplay
                autoPlay : <?php echo $this->getData('slider_autoplay') ? 'true' : 'false'?>,
                lazyLoad : <?php echo $this->getData('slider_lazyload') ? 'true' : 'false'?>,
                stopOnHover : <?php echo $this->getData('slider_stoponhover') ? 'true' : 'false'?>,
                mouseDrag : <?php echo $this->getData('slider_mouse_drag') ? 'true' : 'false'?>,
                touchDrag : <?php echo $this->getData('slider_touch_drag') ? 'true' : 'false'?>,    
             
                // Navigation
                navigation : <?php echo $this->getData('slider_navigation') ? 'true' : 'false'?>,
                navigationText : ["<?php echo $this->__('Previous')?>", "<?php echo $this->__('Next')?>"],
                pagination : <?php echo $this->getData('slider_pagination') ? 'true' : 'false'?>,
                paginationNumbers: <?php echo $this->getData('slider_pagination_numbers') ? 'true' : 'false'?>,
             
                // Responsive 
                responsive: true,
                items : <?php echo $this->getData('slider_items') ? $this->getData('slider_items'): 4 ?>, /*items above 1200px browser width*/
                itemsDesktop : [1199,<?php echo $this->getData('slider_items_desktop') ? $this->getData('slider_items_desktop') : 4 ?>], /*//items between 1199px and 981px*/
                itemsDesktopSmall : [991,<?php echo $this->getData('slider_items_desktop_small') ? $this->getData('slider_items_desktop_small') : 3 ?>],
                itemsTablet: [767,<?php echo $this->getData('slider_items_tablet') ? $this->getData('slider_items_tablet') : 2 ?>],
               //itemsTabletSmall : [599,<?php echo $this->getData('slider_items_tablet_small') ? $this->getData('slider_items_tablet_small') : 2 ?>],
                itemsMobile : [320,<?php echo $this->getData('slider_items_mobile') ? $this->getData('slider_items_mobile') :  1?>],
             
                // CSS Styles
                baseClass : "owl-carousel",
                theme : "owl-theme",
                addClassActive : true,
                scrollPerPage : <?php echo $this->getData('slider_scrollperpage') ? 'true' : 'false'?>
          });
      }
	}
	jQuery(document).ready(function() {
	   em_slider_init_widget_<?php echo $idJs ?>();
	});
//]]>
</script>
<?php endif;?>