<?php
    return array(
        'screen-large-desktop' => '1200px',
        'screen-desktop' => '992px',
        'screen-tablet' => '768px',
		
    	'page_bg_color' => '#ffffff',
        'page_bg_position' => "0 0",
    	'page_bg_repeat' => 'repeat',
        'box_shadow' => '0 0px 10px #dddddd ',
        'box2_shadow' => '0px 1px 8px #edeaea inset',
    	'rounded_corner' => '0px',
        
		'google_fonts' => "Playfair Display,Open Sans",
        'google_fonts_weights' => "100,200,300,400,500,600,700,800",
    	'general_font' => "normal 13px/1.35 Open Sans, Arial, Helvetica, sans-serif",
    	'h1_font' => "500 30px/1.35 Playfair Display, Arial, Helvetica, sans-serif",
    	'h2_font' => "500 24px/1.35 Playfair Display, Arial, Helvetica, sans-serif",
    	'h3_font' => "500 18px/1.35 Roboto Slab, Arial, Helvetica, sans-serif",
    	'h4_font' => "500 15px/1.35 Roboto Slab, Arial, Helvetica, sans-serif",
    	'h5_font' => "400 12px/1.35 Roboto Slab, Arial, Helvetica, sans-serif",
        'h6_font' => "400 10px/1.35 Open Sans, Arial, Helvetica, sans-serif",        
        'banner_title_font' => "500 44px Playfair Display, Arial, Times New Roman, serif",
		
        'header_bg_color' => '#ffffff',
        'header_bg2_color' => '#222222',
    	'header_bg_position' => "0 0",    	
    	'header_bg_repeat' => 'repeat',
    	'header_text_color' => '#666666',
        'header_text2_color' => '#ffffff',			
        'header_text3_color' => '#999999',			
        'header_text4_color' => '#b95b79',
        'header_line_color' => '#dcdcdc',
        'header_line2_color' => '#000000',
        'header_line3_color' => '#bdbdbd',
		 
		'topmenu_bg_color' => 'transparent',
		'topmenu_bg2_color' => '#000000',
    	'topmenu_hover_bg_color' => 'transparent',
    	'topmenu_text_color' => '#000000',
    	'topmenu_text2_color' => '#ffffff',
    	'topmenu_hover_text_color' => '#b95b79',
    	'topmenu_line_color' => 'transparent',
        'topmenu_font' => "500 15px/1.35 Roboto Slab, Arial, Helvetica, sans-serif",
		
		
    	'dropmenu_bg_color' => '#ffffff',    	
    	'dropmenu_text_color' => '#666666',
        'dropmenu_text2_color' => '#999999',
        'dropmenu_hover_text_color' => '#b95b79',
        'dropmenu_line_color' => '#bdbdbd',
		'dropmenu_font' => "normal 12px/1.35 Open Sans, Arial,Helvetica,sans-serif",
        
        'body_bg_color' => '#ffffff',
        'body_bg2_color' => '#63360e',
        'body_bg3_color' => '#000000',   
        'body_bg4_color' => '#b95b79',   
        'body_bg5_color' => '#bdbdbd',   
		'body_bg6_color' => '#5e92be', /* background lable new*/  
    	'body_bg_position' => "0 0",
    	'body_bg_repeat' => "repeat",
        'body_text_color' => '#999999',
        'body_text2_color' => '#666666',	
        'body_text3_color' => '#000000',	
        'body_text4_color' => '#b95b79',	
        'body_text5_color' => '#ffffff',	
        'body_line_color' => '#cecece',
        'body_line2_color' => '#edf2ee',
        'body_line3_color' => '#818181',
        
        'footer_bg_color' => '#222222',
        'footer_bg2_color' => '#b95b79',
    	'footer_bg_position' => '0 0',
    	'footer_bg_repeat' => 'repeat',
        'footer_text_color' => '#999999',
        'footer_text2_color' => '#ffffff',
        'footer_text3_color' => '#474747',
        'footer_text4_color' => '#b95b79',
        'footer_line_color' => '#c26f89',
        'footer_line2_color' => '#ffffff',
        	        
        'btn1_bg_color' => '#ffffff',
    	'btn1_text_color' => '#000000',
    	'btn1_line_color' => '#dedede',
    	'btn1_font' => "500 12px/1.35 Open Sans,Arial, Helvetica, sans-serif",
        
        'btn2_bg_color' => '#000000',
    	'btn2_text_color' => '#ffffff',
    	'btn2_line_color' => '#000000',
    	
        
        'btn3_bg_color' => 'transparent',
    	'btn3_text_color' => '#b95b79',
    	'btn3_line_color' => '#b95b79',
    	'btn3_font' => "500 12px/1.35 Open Sans,Arial, Helvetica, sans-serif",   

		'btn4_bg_color' => '#b95b79',
    	'btn4_text_color' => '#ffffff',
    	'btn4_line_color' => '#b95b79',
    	'btn4_font' => "500 12px/1.35 Open Sans,Arial, Helvetica, sans-serif",
		
		'btn5_bg_color' => 'transparent',
    	'btn5_text_color' => '#ffffff',
    	'btn5_line_color' => '#ffffff',
    	'btn5_font' => "500 18px/1.35 Roboto Slab, Arial, Helvetica, sans-serif",
		
		'btn6_bg_color' => '#ffffff',
    	'btn6_text_color' => '#000000',
    	'btn6_line_color' => '#ffffff',
    	'btn6_font' => "500 18px/1.35 Roboto Slab, Arial, Helvetica, sans-serif",        
		
    );
?>