<?php	
	$setting = Mage::helper('em0120settings');
	$checkmobile = $setting-> checkMobilePhp();
 ?>
<?php if (!$checkmobile):?>
<div class="qrcode hidden-tablet visible-sm visible-md visible-lg">
	<ul id="qr_code">
		<li class="qr_code_name">
            <a href="javascript:void(0)">
                <span>qrcode</span>
                <img style="display: none;" src="<?php echo $this->getSkinUrl('images/media/demo/qrcode-demo-adore.png'); ?>" alt="" title="" />
            </a>
        </li>
	</ul>
</div>
<?php endif;?>